### ISSUE TITLE
Prepare for jvm.options.d support

### ISSUE THREAD

**Issue by dliappis** [elastic/rally-teams#43]
With https://github.com/elastic/elasticsearch/pull/51882 it's possible to specify customizations currently living in `jvm.options` to `jvm.options.d/`.

Since:

> In future versions of Elasticsearch, we can consider removing the root jvm.options file (instead, providing all options there as system JVM options).

we should be proactive and prepare for it before it gets enforced.

**Comment by danielmitterdorfer** [comment]
@hub-cap this issue has been stalled for a while but I think it is important that we will change this proactively. Can you please prioritize this accordingly and address it? IMHO we also need a change in Rally to make this work because Rally will currently delete the default configuration assuming that it will be overridden later on, see https://github.com/elastic/rally/blob/635757e4ff70227c976febbdfeca582c6cb6a944/esrally/mechanic/provisioner.py#L181.

**Comment by hub-cap** [comment]
As discussed, we will do the following to ensure BWC with old versions of rally.

### Phase 1

Rally master
 - remove the "wipe config dir"

Rally Teams
 - create a `7.7` branch
 - Put all existing templated changes from the `jvm.options` into a `jvm.options.d/file` in both `7.7` and `master` (discuss naming)
 - Ensure the `jvm.options` file looks the same as a `jvm.options` file that comes stock w/ an elasticsearch download for `7.7` and `master`

### Phase 2

To happen at a later date, once users have upgraded rally

Rally Teams
 - remove the `jvm.options` file in `7.7` and greater.

**Comment by hub-cap** [comment]
I think ive hit a snag, albeit a minor one. When I run rally w/o any config changes, with standard options, I do not get a gc file. Elasticsearch [sets a standard Xlog line](https://github.com/elastic/elasticsearch/blob/master/distribution/src/config/jvm.options#L66), and so I use `-Xlog:disable` to turn it off in our config.d file. This is what happens.


 `esrally --kill-running-processes --revision=1412e80 --pipeline=from-sources-skip-build --runtime-jdk=bundled `

* No file is created

` esrally --kill-running-processes --revision=1412e80 --pipeline=from-sources-skip-build --runtime-jdk=bundled --team-path=../rally-teams `
* output of the curl jvm command
  * `-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m`
  * followed by
  * `-Xlog:disable`
* files created
```
 find ~/.rally/benchmarks/races/*/rally-node-0 -name '*gc*'           
/home/baz/.rally/benchmarks/races/f2345702-bd84-486b-9ce3-07a8b1264491/rally-node-0/install/elasticsearch-8.0.0-SNAPSHOT/logs/gc.log.00
/home/baz/.rally/benchmarks/races/f2345702-bd84-486b-9ce3-07a8b1264491/rally-node-0/install/elasticsearch-8.0.0-SNAPSHOT/logs/gc.log
```

but the files are empty, 

```
0 0 0 /home/baz/.rally/benchmarks/races/f2345702-bd84-486b-9ce3-07a8b1264491/rally-node-0/install/elasticsearch-8.0.0-SNAPSHOT/logs/gc.log.00
0 0 0 /home/baz/.rally/benchmarks/races/f2345702-bd84-486b-9ce3-07a8b1264491/rally-node-0/install/elasticsearch-8.0.0-SNAPSHOT/logs/gc.log
0 0 0 total
```

I do not consider this a deal breaker, and would rather leave empty artifacts behind than try to do some sed magic on the stock jvm.options file Elasticsearch provides. Thoughts?

**Comment by hub-cap** [comment]
I will be doing the work for 7.7/7.8 next, but here is a preview for what the work looks like for master, I just am choosing not to PR it until I get 7.7/7.8 up to snuff. https://github.com/hub-cap/rally-teams/pull/new/8_options.d

**Comment by hub-cap** [comment]
after discussing the differences that were needed to ensure the `jvm.options` file distributed by Elasticsearch do not adversely affect our rally benchmarks, we have decided not to add support for a config.d file, and instead continue to overwrite the default jvm.options file provided by Elasticsearch. 

A takeaway that is still TBD is for the performance team to come up with a way to monitor changes to the jvm.options file in the elasticsearch repo, so there is less cognitive load associated w/ manually checking the file on occasion. This will likely be a CI job in the future.
